name: http_auth
description: Dart http middleware for HTTP Basic and Digest authentication
version: 0.2.8
homepage: https://github.com/marcoesposito1988/http_auth
author: Marco Esposito <marcoesposito1988@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  http: ">=0.9.0 <1.0.0"
  crypto: ">=2.0.0 <2.2.0"
  convert: ">=2.1.0 <2.2.0"

dev_dependencies:
  test: '>=1.0.0 <2.0.0'
