name: http_auth
description: Dart http middleware for HTTP Basic and Digest authentication
version: 1.0.1
homepage: https://github.com/marcoesposito1988/http_auth

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  http: ">=0.9.0 <2.0.0"
  crypto: ">=2.0.0 <4.0.0"
  convert: ">=2.1.0 <4.0.0"

dev_dependencies:
  test: '>=1.0.0 <2.0.0'
  pedantic: ">=1.7.0 <2.0.0"
